spring.datasource.url=jdbc:postgresql://postgres:5432/stellio_search
spring.datasource.username=stellio
spring.datasource.password=stellio

spring.r2dbc.url=r2dbc:postgresql://postgres:5432/stellio_search
spring.r2dbc.username=stellio
spring.r2dbc.password=stellio

spring.flyway.url=jdbc:postgresql://postgres:5432/stellio_search
spring.flyway.user=stellio
spring.flyway.password=stellio

spring.kafka.bootstrap-servers=kafka:9092

server.port=8080