services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto
    restart: always
    networks:
      - external_network
    expose:
      - '1883'
      - '9001'
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    command: mosquitto -c /mosquitto/config/mosquitto.conf

volumes:
  mosquitto_data:

networks:
  external_network:
    external: true