services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto
    restart: always
    networks:
      - external_network
    expose:
      - '1883'
      - '9001'
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -E -t '$SYS/broker/uptime' -C 1 -W 2 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mosquitto_data:

networks:
  external_network:
    external: true