services:
  ditto:
    image: eclipse/ditto:latest
    hostname: ditto
    networks:
      - default
    ports:
      - "8080:8080"  # Ditto API
    environment:
      DITTO_MQTT_CONNECTIONS_MOSQUITTO_URI: tcp://mosquitto:1883
      DITTO_MQTT_CONNECTIONS_MOSQUITTO_CLIENT_ID: ditto
      DITTO_MQTT_CONNECTIONS_MOSQUITTO_USERNAME: ditto-user
      DITTO_MQTT_CONNECTIONS_MOSQUITTO_PASSWORD: ditto-pass
      DITTO_MQTT_CONNECTIONS_MOSQUITTO_TOPICS: "sensors/#"
      DITTO_PERSISTENCE_MONGO_HOST: mongodb
      DITTO_PERSISTENCE_MONGO_PORT: 27017
      DITTO_PERSISTENCE_MONGO_DB: ditto
    depends_on:
      - mongodb
      - mosquitto

  mongodb:
    image: mongo:4.4
    networks:
      - default
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    networks:
      - default
    expose:
      - '1883'
      - '9001'
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - mosquitto_data:/mosquitto/config

volumes:
  mongodb_data:
  mosquitto_data:

networks:
  default:
    driver: overlay
    attachable: true
