services:
  docker-host:
    image: docker:dind
    container_name: docker-host
    privileged: true
    volumes:
      - ./ditto:/root/ditto
      - ./setup.sh:/root/setup.sh
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: ["sh", "-c", "./root/setup.sh"]